### ISSUE TITLE
Customize 404 page

### ISSUE THREAD

**Issue by nikdragovic** [emory-libraries/dlp-lux#278]
## Wireframe
![Lux Beta Wireframes - Working Document - 404 page.png](https://images.zenhubusercontent.com/5ba135cf945aef49576d50f2/f174d2ef-a1fe-48eb-be23-575a8e2c3bb9)

## Acceptance Criteria
- [ ] User reaches this page when a domain cannot be found.
- [ ] User reaches this page when following a valid, shared link to Private objects and others that their authentication status does not entitle them to see.
- [ ] User reaches this page when following search result from records that their authentication status does not entitle them to see.

**Comment by maxkadel** [comment]
* I think the header "Restricted Page" could be confusing, because we're also using this as a 404 page, which is specifically for "not found." 
* We could change it to be a 401 page, which is for restricted pages. The reason we didn't default to that is that it's more secure, if you're trying to keep objects super secret, to have the same behavior whether someone is authorized to see something or if it doesn't exist. That way a hacker can't send a whole bunch of random strings, find a thing that exists, and then start working on getting more information about that. But, since we're currently saying that those objects will be discoverable, but not viewable, that same hacker can just see that they exist on the search page in Lux, so that reason is moot.
* The language around "the contact information on the object's collection page" - how would the unauthenticated user get to the object's collection page, or know what collection it's in, if they can't open the show page?
* Is there a reason to describe where to find the log in link, rather than simply linking to the log in page in the text? (for instance, does someone using a screenreader know how to get back to the upper right corner of the page?)

**Comment by nikdragovic** [comment]
![Lux Beta Wireframes - Working Document - 404 page (2).jpeg](https://images.zenhubusercontent.com/5ba135cf945aef49576d50f2/34aeecc6-9aaa-4943-8ff8-e723bb0be812)

Wireframe updated according to various feedback.

**Comment by maxkadel** [comment]
![image.png](https://images.zenhubusercontent.com/5d51624a5b89150001ae0b03/bec8d6d4-4947-4503-b162-9fc3d5795165)

**Comment by nikdragovic** [comment]
@maxkadel Thanks, this looks great. Just one question - do you know why the header appears when trying to access something restricted (https://digital-test.library.emory.edu/catalog/4407wm37qp-cor) but does not appear when putting in a bad URL (https://digital-test.library.emory.edu/catalog/123)?

**Comment by maxkadel** [comment]
@nikdragovic Thanks! 

I've specifically told Lux to render a 404 when someone is _denied access_, and have asked it to use the application layout when rendering the page in this scenario.

I suspect we could define more scenarios in which the error pages use the Lux layout. There are some pros and cons to doing that that Mark or Bess might be able to lay out more clearly. 

The risk to using the layout in more scenarios is that if something is going badly wrong with the application, the user would not be able to load *anything*, rather than the application being able to render an error page that could give the user more information.

**Comment by nikdragovic** [comment]
@maxkadel Thanks, This is helpful. Perhaps if we are able to have that discussion, I can be apprised of the range of error pages that a user might encounter which might not be optimal. I'm thinking specifically of what we saw with digital.library.emory.edu for non logged-in users, which may become a moot point.
