### ISSUE TITLE
Setup Continuous Deployment for digtial-arch

### ISSUE THREAD

**Issue by rotated8** [emory-libraries/dlp-lux#30]
This includes a cron job and bash script to run a capistrano localhost deploy daily

**Comment by bess** [comment]
This is almost done, but hitting permissions issues. @SolomonHD I will need your help to resolve those.

**Comment by bess** [comment]
There is a ruby script in `/home/ec2-user` called `update_lux.rb`
Ideally, there should be a user local to that box who can run a `cap deploy` command (which is really all that script does), which can be scheduled via cron. I thought it would make sense to do that as the ec2-user, but it isn't a requirement that the script be run by any particular user, as long as the deploy process works.

**Comment by mprefer** [comment]
I made some changes to the script /home/ec2-user/upgrade_lux.rb.
I made it a bash script, because I am an old school bash'er!

Script is currently located at /usr/local/bin/update_lux.sh
It is currently set in the 'deploy' user's crontab to run at 6:05 UTC, which I hope is 1:05 EST.
It spits out stdout in /tmp/update_lux.out, stderr in /tmp/update_lux.err.
Each of those files gets overwritten each run, but if needs be, can create a log that appends.
