### ISSUE TITLE
SPIKE: Enable bookmarks for non-logged in user

### ISSUE THREAD

**Issue by nikdragovic** [emory-libraries/dlp-lux#308]
Timeboxed investigation - determine if we can implement this by turning on a setting. We don't want to do extensive development for this.

## Acceptance Criteria
- [ ] Time estimate for enabling bookmark feature for non-logged in user. Based on anticipated time, team will configure this feature or advise PO to follow up with ticket to adjust the error page a non-logged in user sees at digital.library.emory.edu/bookmarks

**Comment by mark-dce** [comment]
FWIW - attempting to access and invalid path like https://digital.library.emory.edu/non-existent-path gives me a 404 - Not Found Error

attempting to access the bookmarks (when I'm not logged in) at  https://digital.library.emory.edu/bookmarks gives me a 500 - Internal Server Error

At a minimum, if we can't get bookmarks working for non-authenticated users, we should have this path give a 404 instead of a 500 error.

It's also probably worth noting that the bookmarks table in lux looks somewhat different from the canonical demo site code
Lux: https://github.com/emory-libraries/dlp-lux/blob/master/db/schema.rb#L15-L25  
Demo Site: https://github.com/projectblacklight/demo.projectblacklight.org/blob/master/db/schema.rb#L15-L24   
This might also be a red-herring because the demo site is based on BL 6.x and Lux is running BL 7.x  (so it may also be worth asking the Blacklight List if there is anyone who has has successes or failures with bookmarks in BL7)

**Comment by nikdragovic** [comment]
Thanks, @mark-dce. That's helpful to know.

The 500 error you encountered is part of the reason this ticket originated, with the thought that we should in some way rectify the 500 error if we didn't implement the bookmarks for non-logged in user and generate a valid path. 

At some point, this ended up getting peeled off into ticket #458 about 500 class errors, which we closed today.

**Comment by fnibbit** [comment]
Max and I were looking through the blacklight code, and enabling bookmarks for unauthenticated users requires having "guest users" defined (through the devise-guests gem for example).  This is not set up in our current system, and adding it is risky/would take time to get right given the complex access controls Lux has.

We can and will figure out giving a more appropriate error (404 rather than 500) when accessing the bookmarks url unauthenticated.
