### ISSUE TITLE
Emory High Download IIIF configuration

### ISSUE THREAD

**Issue by nikdragovic** [emory-libraries/dlp-lux#314]
## Acceptance Criteria
 - [x] Files in viewer should be configured to display at full quality.
 - [x] Visible only to authenticated users

**Comment by maxkadel** [comment]
Implementation note: 
When running a local web server on development machine, *with* "Access-Control-Allow-Origin" set, and putting url for manifest on local server (`http://localhost:3002/552w3r228t-cor/manifest`) into universalviewer.io example Universal viewer

![image.png](https://images.zenhubusercontent.com/5d51624a5b89150001ae0b03/a142dc8a-e2ed-4cb8-b8fe-1a6f3d1a9e96)

**Comment by fnibbit** [comment]
Thoughts about cookies for gating the curate iiif proxy:
proof-of-concept achieved -- on login, lux sets a cookie; curate reads that cookie to check for permission to serve "Emory High Download" files.
next step: prevent spoofing of this cookie. Simple cookies are spoofable. Standard Rails signed or encrypted cookies use the application's secret key to verify/decrypt the cookie; since a curate instance and a lux instance will have different secret keys, curate can't verify/decrypt these types of cookies set by lux.  
Idea #1: Set up an ActiveSupport::MessageVerifier in lux, put a serialized MessageVerifier message in the cookie.  Curate reads the cookie, sends the content to lux to ask if it's legit before serving the file.  references: https://medium.com/@michaeljcoyne/understanding-the-secret-key-base-in-ruby-on-rails-ce2f6f9968a1  https://api.rubyonrails.org/v5.2.4.1/classes/ActiveSupport/MessageVerifier.html  Advantage: all the pieces for implementing this are ready to hand.  Disadvantage: extra communication round-trips.
Idea #2: This seems like a job for the public-key/private-key model -- lux uses its secret to sign the cookie in a way that curate can verify using a public key published by lux, which curate caches and only updates once in a while.  (like ssh or pgp).  Advantage: fewer round trips.  Disadvantage: I dunno how to do it from scratch and don't currently know where the pieces are to assemble it from.

**Comment by maxkadel** [comment]
With cookie, gotten by logging in to Lux
![image](https://user-images.githubusercontent.com/45948126/77006063-34043f00-6938-11ea-84da-81e929e9069e.png)

Without cookie (incognito window)
![image](https://user-images.githubusercontent.com/45948126/77004724-f8687580-6935-11ea-9ffb-cc106a570ffb.png)

**Comment by maxkadel** [comment]
When logged in to Lux
![image.png](https://images.zenhubusercontent.com/5d51624a5b89150001ae0b03/58784d16-24b6-493b-8e19-e2674345cace)

In Incognito Window
![image.png](https://images.zenhubusercontent.com/5d51624a5b89150001ae0b03/6e67b028-a156-4cf0-9cdb-90157f3f2864)
