### ISSUE TITLE
Build a solr index with representative sample data

### ISSUE THREAD

**Issue by RachelDCE** [emory-libraries/dlp-lux#34]
We have a shareable solr index that has 15-30 solr documents for works created by Curate. These should all be public.

**Comment by bess** [comment]
I made a snapshot of the yellowbacks data from curate-qa.curationexperts.com. It is more than 30 solr documents (a lot more) but still seems manageable and I think it will be good to test with something that resembles a real curate index. I made a rake task so that this data can be easily loaded in development, and added instructions for doing that to the README.

Note: This is the same data sample that has been loaded into the solr indexes for digital-test, digital-arch, and digital.library.emory.edu
