### ISSUE TITLE
Style Facets

### ISSUE THREAD

**Issue by maxkadel** [emory-libraries/dlp-lux#344]
- [ ] It looks like the attached screenshot, and uses official Emory pattern library
- [ ] Try to change color - facet background light gray (#D0DEFD), Facet label text and Browse All Items Emory Blue (#082B73) 
- [ ] It uses Heading 5 Alternate in [typography] (http://template.library.emory.edu/styleguide/patternlibrary/current/?p=viewall-meta-typography) for "Browse All Items" 

* http://template.library.emory.edu/styleguide/patternlibrary/current/?p=all
* http://emilyporter.net/emory/blacklight-headerA-4.html
* [Design system colors](https://drive.google.com/file/d/1MpIKYe6YpeS8qpPNqNohKRklloFF2_2m/view?usp=sharing)
* [Detailed color guide](https://www.figma.com/file/B7WWVWaPZOsvffwAbDXMf1cb/Emory-System?node-id=0%3A1)
* [Bootstrap Mapping](https://docs.google.com/spreadsheets/d/1-sbatCXlB7ysNHPrj3vT2mBy4nufx1ovlG7UwX2sdo8/edit?usp=sharing)

![image.png](https://images.zenhubusercontent.com/5d51624a5b89150001ae0b03/d70ebbb8-a218-4a5f-bd06-a9c4d8df4e76)

**Comment by wulman16** [comment]
**Progress as of 3/31:**
![Screen Shot 2020-03-31 at 1.51.26 PM.png](https://images.zenhubusercontent.com/5d653d8e0845ad5f24bad9f8/6eedda8d-462b-4519-bbb7-3b8db5ae8321)

**Comment by nikdragovic** [comment]
@wulman16 If possible, it would be great to remove the word "Locations" from the facet "Subject - Geographic Locations." 

Since there appears to be a lot of text flowing onto multiple lines, it would also help the display of the facet values themselves if we could reduce the font size and possibly the space between those values and the numerical counts. I'm happy to move this into a Visual Styling Fixes ticket if you'd rather move on to more substantial work.

**Comment by wulman16** [comment]
@nikdragovic It's a small amount of work left, so we can keep it on this ticket and move it back to in progress.

**Comment by wulman16** [comment]
![Screen Shot 2020-04-02 at 9.48.29 AM.png](https://images.zenhubusercontent.com/5d653d8e0845ad5f24bad9f8/f46a3028-d31f-40a2-9c0f-2ce7c19885e5)

**Comment by lovinscari** [comment]
I am going to accept this as is after reviewing with Emily. However, we will want to review all design elements (including colors) post-beta and make some changes.
