### ISSUE TITLE
Keywords field improperly combines terms for linked browsing

### ISSUE THREAD

**Issue by nikdragovic** [emory-libraries/dlp-lux#374]
In this example, clicking a subject displays the proper filtering in the search header, but improperly adds multiple facet filters, meaning only one result is typically found. Keywords do not work:

https://digital-test.library.emory.edu/catalog/7956djh9xt-cor

Same behavior here: 

https://digital-test.library.emory.edu/catalog/013mw6m90m-cor

Original tickets are #330 and #351

**Comment by maxkadel** [comment]
@nikdragovic - I see that keywords aren't working, we can look into that.

Could you give more context on the "Subjects"? I think this may be a specificity of subject when cataloged issue, rather than a technical issue. 

When I look at https://digital-test.library.emory.edu/catalog/798mcvdnd8-cor and click on "Bicycle racing" I only get one result, and see the other Topic facets in the facet box. 
![image](https://user-images.githubusercontent.com/45948126/75373633-a5e8eb80-5898-11ea-8543-5731b4851338.png)

However, if I go back to https://digital-test.library.emory.edu/catalog/798mcvdnd8-cor then click on "African American Men" in the Subject-Topics section, I get 33 results
![image](https://user-images.githubusercontent.com/45948126/75373721-d4ff5d00-5898-11ea-988b-10631fc120bc.png)

So, the reason you're not seeing multiple results on your test items is because only one object in the ingested content has that (very specific) subject.

**Comment by nikdragovic** [comment]
Here's an example of the Keyword field links not working correctly: https://digital-test.library.emory.edu/catalog/037hqbzkhj-cor

**Comment by nikdragovic** [comment]
Example above is actually rendering correctly. Will search for additional examples of errors.

**Comment by nikdragovic** [comment]
I'm closing this issue, since the display looks correct for this object: https://digital.library.emory.edu/catalog/883xsj3v3s-cor
