### ISSUE TITLE
Update the 404 page content and styles

### ISSUE THREAD

**Issue by eporter23** [emory-libraries/dlp-lux#480]
## Acceptance criteria

- [ ] Use the same page styles included for static pages (About, Contact) - reference example: https://libraries.emory.edu/contact/office-department-contacts.html
- [ ] Adjust text as noted in the working content document below

[Content and style](https://docs.google.com/document/d/1L9cvAwth5bBaFgzOOn8HPcXpIAuvy7xYADLN_v3sbcM/edit#heading=h.mlg8gfmkiwd9)
[Static page template](https://docs.google.com/document/d/1xRp_yZi-44z4K8pUMbZahXVQBlBo43wT47lAGU5eoeE/edit)

**Comment by eporter23** [comment]
@nikdragovic @lovinscari I hope this is not a duplicate but I couldn't find a ticket to update the 404 page content so I created this one.

**Comment by bwatson78** [comment]
![Screen Shot 2020-04-15 at 10.25.15 AM.png](https://images.zenhubusercontent.com/5e6f6c00c3241244877b4aea/d8e99f84-a8cf-4ea0-8708-764ce51181b2)

**Comment by bwatson78** [comment]
PR for changes above: https://github.com/emory-libraries/dlp-lux/pull/498

**Comment by nikdragovic** [comment]
@bwatson78 @wulman16 I'm looking at test, v0.7.4 

For an invalid path (https://digital-test.library.emory.edu/123), the page looks correct.

For an access restricted item, the old version is still displaying:

https://digital-test.library.emory.edu/catalog/982x3ffbh4-cor (when not logged in)

I'm assuming we just need to make an update since the latter case is not a "true" 404.

**Comment by bwatson78** [comment]
@nikdragovic I'll get that working for you.

**Comment by bwatson78** [comment]
![Screen Shot 2020-04-16 at 9.37.38 AM.png](https://images.zenhubusercontent.com/5e6f6c00c3241244877b4aea/1391df56-da78-4cae-9bfb-3c4c853bd35a)

Notice the url in the bar.
