### ISSUE TITLE
Don't hard-code date 

### ISSUE THREAD

**Issue by maxkadel** [emory-libraries/dlp-lux#554]
https://github.com/emory-libraries/dlp-lux/blob/b2015700bbf326f1a232ea8958502ef918066c97/app/views/blacklight_range_limit/_range_limit_panel.html.erb#L82

## Acceptance Criteria
- [x] Change range_end to something that will not be outdated as the current year changes.

**Comment by bwatson78** [comment]
Just a heads-up: This is almost impossible to test (writing an expectation that this will always display the current year as the end year range). When I researched this gem to try to get it working for Curate, I found that the code is written to always prefer Solr Stats' `min/max` for each data field rather than use either `assumed_boundaries` (set in the catalog_controller) or the values set in the `range_limit_panel_url` call in the `range_limit_panel` partial override.

**Comment by rotated8** [comment]
You can use `Date.today.year` to test

**Comment by bwatson78** [comment]
After speaking with Collin, he decided that I should remove the setting of those arguments since they don't factor into how the gem processes the range.

**Comment by bwatson78** [comment]
PR made: https://github.com/emory-libraries/dlp-lux/pull/644

**Comment by bwatson78** [comment]
No screenshot needed since this doesn't affect any UI.
