### ISSUE TITLE
Unexpected behavior of "unknown" value in Date facet

### ISSUE THREAD

**Issue by nikdragovic** [emory-libraries/dlp-lux#611]
When clicking "unknown" from the homepage; a search results page is presented, but with the Featured Collections instead of the results for that query. The Date facet disappears from the facet list.

Destination from this action is: https://digital.library.emory.edu/?range%5Byear_for_lux_isim%5D%5Bmissing%5D=true

When clicking "unknown" from a search results page, the Date facet disappears from the facet list.

Destination from this action is: https://digital.library.emory.edu/?q=&range%5Byear_for_lux_isim%5D%5Bmissing%5D=true&search_field=common_fields&utf8=%E2%9C%93

![Screen Shot 2020-05-20 at 9.14.07 AM.png](https://images.zenhubusercontent.com/5ba135cf945aef49576d50f2/b5d6868a-edd0-4caf-a72a-c791cfcd87ae)
![Screen Shot 2020-05-20 at 9.15.52 AM.png](https://images.zenhubusercontent.com/5ba135cf945aef49576d50f2/cb262198-f006-4644-8860-8f8210765060)

**Comment by bwatson78** [comment]
@nikdragovic I have reached a solution that makes the "unknown" link work in both places mentioned and reliably supplies a constraint button on top. Unfortunately, the "Date" facet still disappears and remains gone until the "X" on the limiter is pressed. The Solr response provides us with an `items` array that only contains references to documents with the value populated. The only reference to documents with that field unpopulated is a number in the stats portion of that field object.

In order to have the date facet stay visible, there are two possible options:

1. have Curate send an items object to Lux that encapsulates all documents that have that value missing, or
2. have Lux create an items object whenever it iterates over the Solr response from curate, 

Either way, I'd estimate 1.5 more days of work for coding and testing.

**Comment by bwatson78** [comment]
@nikdragovic An example of what I'm referring to:

![Screen Shot 2020-05-28 at 9.54.43 AM.png](https://images.zenhubusercontent.com/5e6f6c00c3241244877b4aea/74f6a9e9-37d8-4d05-beed-cea0712e5717)

**Comment by bwatson78** [comment]
@nikdragovic And a video of the behavior:

**Comment by rotated8** [comment]
After discussion, it appears the Date facet does not support "OR" querying, so having the the facet disappear when "unknown" is selected is correct behavior.

This is perhaps surprising compared to other facets, where you could select multiple, and an item that matched any of selections would show up in the results. With the date facet, once you apply a date range, the facet does not give you the ability to add another, only to update the one you set originally.

As an example, a user can, on the homepage, open the Date facet, change the range to 1800-2000, click apply, and see results. At that point, the current range can be shrunk using the sliders, or grown or shrunk using the text fields, but another range cannot be added. A user cannot search for works with dates between 1800-1825 OR 1850-1875. A side effect of this is that once a numeric range is specified, 'unknown' dates can no longer be added to the query either.

**Comment by nikdragovic** [comment]
Thanks @rotated8! Closing this bug ticket as @bwatson78 has satisfied the scope as written; we now have a potential enhancement.

**Comment by bwatson78** [comment]
PR made: https://github.com/emory-libraries/dlp-lux/pull/615

![Screen Shot 2020-05-28 at 9.54.43 AM.png](https://images.zenhubusercontent.com/5e6f6c00c3241244877b4aea/41a2f47d-194a-49df-8cf2-17e4ecb736b9)
