### ISSUE TITLE
Display Access Restriction Note for low res items

### ISSUE THREAD

**Issue by nikdragovic** [emory-libraries/dlp-lux#628]
Second option is preferred; ticket may need to be re-estimated. 

## Acceptance Criteria
- [x] Preferred option: When Visibility is Public Low View, display “This item is provided at low resolution only. Downloads are not permitted for this material.” and if Visibility is Emory Low Download, display: “This item is provided at low resolution only.” Display the message in the "About this Item" metadata grouping, above "Date Created."
- [ ] Secondary option: When the Access Restriction field (access_restriction_notes) is populated, display the field in the "About this Item" metadata grouping, above "Date Created."

**Comment by eporter23** [comment]
@nikdragovic and team, as an alternative idea, instead of manually adding metadata for each item that may have low res delivery, could we instead have an application-generated message that is triggered by the Visibility assigned, for those setting that deliver low resolution images? This would display as described above, but would not require metadata fields to be populated (especially since visibility settings applied to items may change over time).

If visibility is Public Low View
Message to display: “This item is provided at low resolution only. Downloads are not permitted for this material.”

If visibility is Emory Low Download:
Message to display: “This item is provided at low resolution only.”

**Comment by bwatson78** [comment]
For 0859cnp5qw-cor: 
![Screen Shot 2020-07-09 at 2.11.36 PM.png](https://images.zenhubusercontent.com/5e6f6c00c3241244877b4aea/8aede5f2-9157-4914-bea7-ef5cc724953d)

For 692t4b8h0w-cor:
![Screen Shot 2020-07-09 at 2.10.49 PM.png](https://images.zenhubusercontent.com/5e6f6c00c3241244877b4aea/fe6033fe-f4a6-4d90-b871-89ad0e8aa317)

**Comment by bwatson78** [comment]
PR made: https://github.com/emory-libraries/dlp-lux/pull/638
