### ISSUE TITLE
Display of Diacritics

### ISSUE THREAD

**Issue by maxkadel** [emory-libraries/dlp-lux#97]
- [ ] Ensure that when a work has proper diacritics in Curate that it displays what those diacritics are in Lux (Fields: Title, creator, description) 

Currently diacritics are not displaying in Lux,  because they are not being saved in the Solr index by Curate. 

![image.png](https://images.zenhubusercontent.com/5d51624a5b89150001ae0b03/a275d4b3-299a-4000-89ed-f5a3ba0d5c81)

![image.png](https://images.zenhubusercontent.com/5d51624a5b89150001ae0b03/952c822f-8f28-44ad-8b03-f629b77c8722)

**Comment by maxkadel** [comment]
This may be an issue with the data going into Curate - [langmuir example data](https://github.com/emory-libraries/cor-data-transfer/blob/master/curate-ingests/2019/in_development/langmuir/langmuir_batch5.csv)

**Comment by wulman16** [comment]
Upon manually creating an object in Curate with fields populated with diacritics, both the show page and the Solr document preserve the diacritics:

![Screen Shot 2019-12-17 at 4.11.44 PM.png](https://images.zenhubusercontent.com/5d653d8e0845ad5f24bad9f8/fea1f71e-0cbd-40fb-90a7-4120d50b8e38)
![Screen Shot 2019-12-17 at 4.12.12 PM.png](https://images.zenhubusercontent.com/5d653d8e0845ad5f24bad9f8/87c5032b-c091-4c6d-9b0d-ce1cc49ad812)

It stands to reason that if pointed to the same Solr document, Lux would not have an issue either. The problem appears to be with the data going into Curate in the first place, which @maxkadel pointed to above. It would not be possible to script a solution to this problem because the encoding in the CSV linked above is not precise enough (e.g., "Laitière revenant du marché" is encoded in the CSV as "Laitie\_re revenant du marche\_", which does not distinguish between e-acute and e-grave).

**Comment by eporter23** [comment]
@wulman16 @maxkadel I confirmed with the Langmuir collection owner today that those diacritics are missing from the source metadata we loaded. We (Emory) can clean those up over time.
